---
name: General checks

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:

jobs:
  spelling-check:
    name: Spell check using typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.30.2

  trailing-whitespaces-check:
    name: Trailing whitespaces check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./test/trailing_spaces.py --Werror $(git ls-files ':!vendor' ':!*.h5')

  newlines-check:
    name: Newlines check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./test/newline_at_eof.py --Werror $(git ls-files ':!vendor' ':!*.h5')
