---
name: Shell checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/shell-checks.yaml'
      - '**.sh'
  workflow_dispatch:

jobs:
  shell-lint:
    name: Shell lint using shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
